---
# tasks file for chrony

- name: install chrony
  yum:
    name: chrony
    state: latest

# - name: configure chrony.conf
#   template:
#     src: chrony.conf.j2
#     dest: /etc/chrony.conf
#   notify: restart chronyd

- name: start chronyd
  service:
    name: chronyd
    state: started
    enabled: yes
