---
# tasks file for creating default domain & project

- name: create admin-openrc.sh script
  template:
    src: admin-openrc.sh
    dest: /root/admin-openrc.sh

- name: create demo-openrc.sh script
  template:
    src: demo-openrc.sh
    dest: /root/demo-openrc.sh

- name: create default domain
  os_keystone_domain:
    name: default
    state: present
    description: default domain
  environment:
    "{{ admin_openrc }}"

- name: create service project
  os_project:
    name: service
    state: present
    description: service project
    domain_id: default
  environment:
    "{{ admin_openrc }}"

- name: create demo project
  os_project:
    name: demo
    state: present
    description: demo project
    domain_id: default
  environment:
    "{{ admin_openrc }}"

# - name: create demo user
#   os_user:
#     name: demo
#     password: stack_pass
#     state: present
#     description: demo user
#     interface: public
#   environment:
#     "{{ admin-openrc.sh }}"

- name: create demo user
  shell: 'openstack user create --domain default --password stack_pass demo && touch /etc/keystone/.demo_user_exists'
  environment:
    "{{ admin_openrc }}"
  args:
    creates: /etc/keystone/.demo_user_exists

- name: create admin role
  os_keystone_role:
    name: admin
    state: present
  environment:
    "{{ admin_openrc }}"

- name: create user role
  os_keystone_role:
    name: user
    state: present
  environment:
    "{{ admin_openrc }}"

- name: associate demo to user role
  os_user_role:
    user: demo
    role: user
    project: demo
    state: present
    region_name: RegionOne
  environment:
    "{{ admin_openrc }}"
