---
# tasks file for keystone

- name: add httpd role
  include_role:
    name: centos/httpd

- name: install keystone
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - openstack-keystone
    - httpd
    - mod_wsgi
    - python2-shade

- name: configure apache for keystone
  file:
    src: /usr/share/keystone/wsgi-keystone.conf
    dest: /etc/httpd/conf.d/wsgi-keystone.conf
    state: link
  notify:
    - restart httpd

# Need to trigger httpd handler
- meta: flush_handlers

- name: copy keystone.conf
  template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf
  notify:
  - restart httpd

- name: create keystone database
  mysql_db:
    name: keystone
    state: present

- name: grant privileges to keystone
  mysql_user:
    check_implicit_admin: yes
    name: "{{ keystonedb_user }}"
    password: "{{ keystonedb_pass }}"
    priv: "{{ keystonedb_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - "localhost"
    - "%"

- name: populate identity database
  shell: 'su -s /bin/sh -c "keystone-manage db_sync" keystone && touch /etc/keystone/.keystone_db_sync_exists'
  args:
    creates:  /etc/keystone/.keystone_db_sync_exists

- include_tasks: bootstrap.yml
- include_tasks: default_domain.yml
