---
# tasks file for neutron-compute

- name: install neutron linuxbridge
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - openstack-neutron-linuxbridge
    - ebtables
    - ipset

- name: copy neutron.conf
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
  notify: restart neutron-linuxbridge-agent

- name: copy linuxbridge_agent.ini
  template:
    src: linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
  notify: restart neutron-linuxbridge-agent

- name: start neutron-linuxbridge-agent service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - neutron-linuxbridge-agent
