---
# defaults file for openstack_controller

hostname: controller

rabbitmq_openstack_username: openstack
rabbitmq_openstack_password: stack_pass

chrony_allow_network: 10.0.0.0
chrony_allow_cidr: 24

admin_openrc:
  OS_USERNAME: admin
  OS_PASSWORD: stack_pass
  OS_PROJECT_NAME: admin
  OS_USER_DOMAIN_NAME: Default
  OS_PROJECT_DOMAIN_NAME: Default
  OS_AUTH_URL: "http://{{ hostname }}:5000/v3"
  OS_IDENTITY_API_VERSION: 3
  OS_IMAGE_API_VERSION: 2

demo_openrc:
  OS_USERNAME: demo
  OS_PASSWORD: stack_pass
  OS_PROJECT_NAME: demo
  OS_USER_DOMAIN_NAME: Default
  OS_PROJECT_DOMAIN_NAME: Default
  OS_AUTH_URL: "http://{{ hostname }}:5000/v3"
  OS_IDENTITY_API_VERSION: 3
  OS_IMAGE_API_VERSION: 2
