---

neutron_hostname: controller

# credentials for neutron service
neutron_user: neutron
neutron_group: neutron
neutron_pass: stack_pass

neutron_internal_url: "http://{{ neutron_hostname }}:9696"
neutron_public_url: "http://{{ neutron_hostname }}:9696"
neutron_admin_url: "http://{{ neutron_hostname }}:9696"
neutron_region: RegionOne


# neutron.conf
# [database]
neutrondb_name: neutron
neutrondb_user: neutron
neutrondb_pass: stack_pass

# [keystone_authtoken]
neutron_keystone_authtoken_auth_uri: "http://{{ neutron_hostname }}:5000"
neutron_keystone_authtoken_auth_url: "http://{{ neutron_hostname }}:5000"
neutron_keystone_authtoken_memcached_servers: "{{ neutron_hostname }}:11211"
neutron_keystone_authtoken_auth_type: password
neutron_keystone_authtoken_project_domain_name: Default
neutron_keystone_authtoken_user_domain_name: Default
neutron_keystone_authtoken_project_name: service
neutron_keystone_authtoken_project_username: neutron
neutron_keystone_authtoken_project_password: stack_pass

# [nova]
neutron_nova_auth_url: "http://{{ neutron_hostname }}:5000"
neutron_nova_auth_type: password
neutron_nova_project_domain_name: default
neutron_nova_user_domain_name: default
neutron_nova_region_name: RegionOne
neutron_nova_project_name: service
neutron_nova_username: nova
neutron_nova_password: stack_pass


# ml2_conf.ini
# [ml2]
neutron_ml2_type_drivers: flat,vlan,vxlan
neutron_ml2_tenant_network_types: vxlan
neutron_ml2_mechanism_drivers: linuxbridge,l2population
neutron_ml2_extension_drivers: port_security
# [ml2_type_flat]
neutron_ml2_type_flat_flat_networks: provider
# [ml2_type_vxlan]
neutron_ml2_type_vxlan_vni_ranges: 1:1000
# [securitygroup]
neutron_ml2_securitygroup_enable_ipset: true


# linuxbridge_agent.ini
# [linux_bridge]
neutron_linux_bridge_physical_interface_mappings: provider:eth2
# [securitygroup]
neutron_securitygroup_enable_security_group: true
neutron_securitygroup_firewall_driver: neutron.agent.linux.iptables_firewall.IptablesFirewallDriver
# [vxlan]
neutron_vxlan_enable_vxlan: true
neutron_vxlan_local_ip: "{{ ansible_eth1.ipv4 }}"
neutron_vxlan_l2_population: true

# l3_agent.ini
# [DEFAULT]
neutron_default_external_network_bridge: ""
neutron_default_interface_driver: linuxbridge

# dhcp_agent.ini
# [DEFAULT]
neutron_default_dnsmasq_config_file: "/etc/neutron/dnsmasq-neutron.conf"
# neutron_default_interface_driver: linuxbridge
neutron_default_dhcp_driver: neutron.agent.linux.dhcp.Dnsmasq
neutron_default_enable_isolated_metadata: true

# metadata_agent.ini
# [DEFAULT]
neutron_nova_metadata_host: "{{ neutron_hostname }}"
neutron_metadata_proxy_shared_secret: METADATA_SECRET
